name: Run test bench

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  run-java-testbench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Run StompTestBench
        run: java java/StompTestBench.java